Fix encoding custom types zero values with omitempty when marshaller exists
goccy/go-json pull request #187
Opened 2021-04-11 18:49 UTC by IncSW

#186

2021-04-12 02:48 UTC, goccy requested changes
Thank you for the contribution !
I made some comments so please check 🙏

2021-04-12 02:48 UTC, goccy commented on internal/encoder/encoder.go
> +	case reflect.Complex64, reflect.Complex128:
Since `complex` value cannot be encoded in JSON, please remove this .

2021-04-12 02:48 UTC, goccy commented on internal/encoder/vm_escaped/vm.go
> +			if code.Nilcheck && encoder.IsNilForMarshaler(iface) {
Probably this condition will not be true in the test cases you added .
( you can see VM opcodes by `fmt.Println(code.CodeSet.Dump())` )

2021-04-14 17:30 UTC, goccy requested changes
Thank you for the correction.
Please add similar code to `vm_debug` package ( [here](https://github.com/goccy/go-json/blob/master/internal/encoder/vm_debug/vm.go#L3662) ).
This is just an addition and you don't have to worry about coverage.

2021-04-14 18:03 UTC, goccy approved these changes
LGTM, Thank you for the contribution !

2021-04-14 18:04 UTC, merged

2021-04-15 09:31 UTC, Dilshat commented
@goccy hi, when is this change going to be released?

2021-04-15 11:12 UTC, goccy commented
@Dilshat Hi, I just released it as v0.4.12 ! Thanks 😄

2021-04-15 11:15 UTC, Dilshat commented
Thanks a lot !👍