remove unnecessary goto
goccy/go-json pull request #212
Opened 2021-05-03 10:50 UTC by IncSW

`go version go1.16 linux/amd64`

```
BenchmarkSkipWhiteSpace/gotoLabel-8   25363138   47.65 ns/op
BenchmarkSkipWhiteSpace/loop-8        25359750   47.43 ns/op
```

`goto` is not needed inside `skipWhiteSpace`

2021-05-03 10:58 UTC, goccy commented
This goto statement is important for improvement performance. Please try to run benchmark

2021-05-03 11:09 UTC, IncSW commented
I checked it in linux and windows, result same, tiny improvements with loop.

2021-05-05 08:28 UTC, IncSW commented
@goccy
https://godbolt.org/z/Kv4o49dT7 assembly is same.

2021-05-05 18:17 UTC, goccy requested changes

2021-05-05 18:17 UTC, goccy commented on decode_slice.go
> +					*(*unsafe.Pointer)(ep) = nil // initialize elem pointer
Please revert this fix.

2021-05-05 18:17 UTC, goccy commented on decode_slice.go
> +					*(*unsafe.Pointer)(ep) = nil // initialize elem pointer
same as above

2021-05-05 18:17 UTC, goccy commented on decode_test.go
> +var (
OK, I don't need these benchmarks, so you can delete this changed .

2021-05-05 18:17 UTC, goccy commented on decode_context.go
> +	for isWhiteSpace[buf[cursor]] {
I had a misunderstanding. This fix is ​​okay 👍

2021-05-05 18:22 UTC, goccy commented
I'm planning to do the refactoring after this, so I don't need to create a PR at this stage.
But this fix is ​​good 👍 Thanks !

2021-05-06 04:10 UTC, goccy approved these changes

2021-05-06 04:10 UTC, merged